### ISSUE TITLE
Implement resetPassword feature

### ISSUE THREAD

**Issue by R-Thibault** [R-Thibault/FollowMyJobs#12]
### Implement resetPassword feature

---

#### **Summary**
- **URL**: `[HTTP POST] /reset-password`
- **Purpose**: Enables users to reset their password by providing their email or username. This feature will send a reset link or code to the user.
- **Authentication**: Not required for initiating the reset; required for completing the reset.

---

### **Tasks**
- [x] Define route for POST /reset-password in the router.
- [x] Implement SendResetLink function in the controller to handle email dispatch with a secure reset token.
- [x] Implement VerifyResetToken function to validate reset token.
- [x] Create a ResetPassword function to update the password securely.
- [x] Add request validation for email format and password strength.
- [x] Write integration tests for the entire flow (request reset, validate token, set new password).

---

#### **Request Data**
<pre><code>json
{
  "email": "string, required" 
}
</code></pre>

#### **Response**

- **Success** (`200 OK`):
  <pre><code>json
  {
     "message": "Password reset link sent successfully to your email."
  }
  </code></pre>

- **Error** (`400 Bad Request`):
  <pre><code>json
  {
    "error": "InvalidEmail",
     "message": "The provided email is invalid." 
  }
  </code></pre>

#### **Token Verification Data**

<pre><code>json 
{
 "token": "string, required", "password": "string, required"
 } 
</code></pre>

Success (200 OK):

<pre><code>json
 { 
 "message": "Password updated successfully." 
} 
</code></pre>

Error (400 Bad Request):

<pre><code>json 
{ 
"error": "InvalidToken", 
"message": "The reset token is invalid or expired."
 } 
</code></pre>

Error (500 Internal Server Error):

<pre><code>json 
{ 
"error": "ServerError",
 "message": "An unexpected error occurred."
 } 
</code></pre>

---

### **Detailed Description**
The Reset Password feature provides users with a secure way to reset their forgotten or compromised passwords. Users initiate the process by entering their email address. A secure link with a time-limited token is sent to their email. The link directs the user to a reset page where they can input a new password. Upon submission, the backend validates the token, updates the password, and invalidates the token.

---

### **Acceptance Criteria**
- [x] Password reset link is sent successfully to valid email addresses.
- [x] Token is validated securely and invalidated after use.
- [x] New password is stored securely (hashed)
- [x] All edge cases (e.g., expired token, invalid email) are handled appropriately.
- [x] 100% test coverage for all new code
- [x] Integration with existing login and authentication systems
---

**Additional Context**
(Optional) Include links to mockups for the login page update, reset email templates, or any relevant documentation.

---

**Labels**:  `feature`,  `API`,
