### ISSUE TITLE
Implement Auth middleware with context

### ISSUE THREAD

**Issue by R-Thibault** [R-Thibault/FollowMyJobs#14]
## [Title]: Implement Auth middleware with context

---

#### **Summary**
- **URL**: `None`
- **Purpose**: Add auth middleware to controlle http Only Cookie to protect routes and implement context for backend
- **Authentication**: require http Only Cookie

---

### **Tasks**
- [x] Create auth_middleware.go
- [x] Define protected routes group

---

#### **Request Data**
<pre><code>json
{
  "withCredential": "true"
}
</code></pre>

#### **Response**
- **Success** ():
  Follow request

- **Error** (`401`):
  <pre><code>json
  {
    "error": "error_type",
    "message": "Invalid token/token expired"
  }
  </code></pre>

---

### **Detailed Description**
The auth_middleware will be use to protecte some route by check the jwtToken contain inside the http Only cookie. Will be a basic httpOnly Cookie token, no refresh token for the moment.

---

### **Acceptance Criteria**
- [x] auth_middleware should return correct error
- [x] Only route defined as protected should pass throught the middleware

---

**Additional Context**
(Optional)

---

**Labels**: `feature`, `backend`, `middleware`

---
