### ISSUE TITLE
Implement UpdateUserProfile Feature

### ISSUE THREAD

**Issue by R-Thibault** [R-Thibault/FollowMyJobs#17]
# Implement UpdateUserProfile Feature

---

#### **Summary**
- **URL**: `[HTTP POST] /update-profile`
- **Purpose**: Allows users to update their profile information such as name, email, and password.
- **Authentication**: Required (User must be logged in)

---

### **Tasks**
- [x] Define route for `POST /update-profile` in the router.
- [x] Implement the `UpdateUserProfile` function in the controller.
- [x] Create a service function `UpdateUserDetails` to handle business logic.

---

#### **Request Data**
```json
{
  "name": "string, optional",
  "email": "string, optional",
  "password": "string, optional"
}
```

#### **Response**
- **Success** (`200 OK`):
  ```json
  {
    "message": "Profile updated successfully",
    "updated_data": {
      "name": "string",
      "email": "string"
    }
  }
  ```

- **Error** (`400 Bad Request`):
  ```json
  {
    "error": "InvalidInput",
    "message": "Provided data is invalid"
  }
  ```

- **Error** (`401 Unauthorized`):
  ```json
  {
    "error": "Unauthorized",
    "message": "User not authenticated"
  }
  ```

- **Error** (`500 Internal Server Error`):
  ```json
  {
    "error": "ServerError",
    "message": "An unexpected error occurred"
  }
  ```

---

### **Detailed Description**
The `UpdateUserProfile` feature allows authenticated users to update specific details of their profile. Only valid fields will be updated, and proper validations will ensure that no invalid data is saved in the database. Password changes will trigger additional security checks.

---

### **Acceptance Criteria**
- [x] Endpoint returns the correct status code and response format.
- [x] Validation errors are properly handled.
- [x] Updates are reflected correctly in the database.
- [x] Sensitive operations (e.g., password update) require additional checks.

---

**Additional Context**
(Optional) This feature is part of the user management module. Ensure it integrates well with the existing authentication system.

---

**Labels**: `feature`, `API`, `user-management`, `documentation`
