### ISSUE TITLE
Implement CRUD Operations for Application

### ISSUE THREAD

**Issue by R-Thibault** [R-Thibault/FollowMyJobs#20]
# Implement CRUD Operations for Application

---

#### **Summary**
- **URL**:
  - `POST /api/applications` – Create a new application
  - `GET /api/applications` – Retrieve all applications
  - `GET /api/applications/{id}` – Retrieve a single application by ID
  - `POST /api/applications/{id}` – Update an existing application
  - `POST /api/applications/{id}` – Delete an application
- **Purpose**: 
  - To provide endpoints for creating, reading, updating, and deleting job application records in the system.
- **Authentication**: 
  - Required for all endpoints.
  - Authentication is managed via HTTP-only cookies.
  - Only authenticated users can perform CRUD operations on their own applications.

---

### **Tasks**
- [x] **Setup Routes**
  - Define API routes for each CRUD operation using Gin.
- [x] **Implement Controllers**
  - Create controller functions for creating, retrieving, updating, and deleting applications.
- [x] **Model Integration**
  - Integrate with the `Application` model using Gorm.
- [x] **Authentication Middleware**
  - Implement middleware to handle authentication via HTTP-only cookies.
  - Ensure that only authenticated users can access the CRUD endpoints.
- [x] **Authorization**
  - Ensure users can only access and modify their own applications.
- [x] **Input Validation**
  - Implement input validation for request data using appropriate validation libraries.
- [x] **Error Handling**
  - Handle error responses appropriately, including edge cases such as non-existent applications or unauthorized access.
- [x] **Testing**
  - Write unit tests for each controller function.
  - Write integration tests for the API endpoints.
- [x] **Documentation**
  - Document the API endpoints with request and response examples.
- [x] **Code Quality**
  - Ensure code follows the project's coding standards and best practices.
  - Perform code reviews and refactoring as necessary.

---

#### **Request Data**

**Create Application (`POST /api/applications`)**
```json
{
  "Url": "string, required",
  "Title": "string, required",
  "Company": "string, optional",
  "Location": "string, optional",
  "Description": "string, optional",
  "Salary": "string, optional",
  "JobType": "string, optional",
  "Applied": "boolean, optional (default: true)",
  "Response": "boolean, optional (default: false)",
  "FollowUp": "boolean, optional (default: false)"
}
```

**Update Application (`POST /api/applications/{id}`)**
```json
{
  "Url": "string, optional",
  "Title": "string, optional",
  "Company": "string, optional",
  "Location": "string, optional",
  "Description": "string, optional",
  "Salary": "string, optional",
  "JobType": "string, optional",
  "Applied": "boolean, optional",
  "Response": "boolean, optional",
  "FollowUp": "boolean, optional"
}
```

---

#### **Response**

- **Success** (`200 OK`):
  ```json
  {
    "id": 1,
    "user_id": 123,
    "url": "https://example.com/job",
    "title": "Software Engineer",
    "company": "Example Corp",
    "location": "New York, NY",
    "description": "Job description here...",
    "salary": "$100,000",
    "job_type": "Full-Time",
    "applied": true,
    "response": false,
    "follow_up": false,
    "created_at": "2024-04-27T10:00:00Z",
    "updated_at": "2024-04-27T10:00:00Z"
  }
  ```

- **Error** (`4XX/5XX`):
  ```json
  {
    "error": "validation_error",
    "message": "Title is required."
  }
  ```

---

### **Detailed Description**
This issue involves creating a complete set of CRUD (Create, Read, Update, Delete) API endpoints for managing job applications within the application backend built with Go and Gin. Each application record is associated with a specific user, ensuring that users can only manage their own applications. Authentication is handled via HTTP-only cookies to secure user sessions.

**Model Definition:**
```go
type Application struct {
	gorm.Model
	UserID      uint
	Url         string `gorm:"not null"`
	Title       string `gorm:"size:255; not null"`
	Company     string `gorm:"size:255"`
	Location    string `gorm:"size:255"`
	Description string
	Salary      string `gorm:"size:255"`
	JobType     string `gorm:"size:255"`
	Applied     bool   `gorm:"default:true"`
	Response    bool   `gorm:"default:false"`
	FollowUp    bool   `gorm:"default:false"`
}
```

**Technology Stack:**
- **Backend Framework**: Go with Gin
- **ORM**: Gorm
- **Authentication**: HTTP-only cookies

**Considerations:**
- **Authentication Middleware**: Utilize Gin middleware to verify HTTP-only cookies and authenticate users for each request.
- **Authorization**: Implement checks to ensure that users can only access and modify their own application records.
- **Input Validation**: Use validation libraries like `go-playground/validator` to validate incoming request data.
- **Error Handling**: Ensure comprehensive error handling for scenarios such as invalid input, unauthorized access, and server errors.
- **Security**: Protect against common web vulnerabilities (e.g., SQL injection, XSS) by following best practices in Go and Gin.
- **Testing**: Ensure high test coverage with both unit and integration tests to maintain reliability.
---

### **Acceptance Criteria**
- [x] All CRUD endpoints (`POST`, `GET`, `PUT`, `DELETE`) are implemented using Go and Gin.
- [x] Endpoints are secured using HTTP-only cookies for authentication.
- [x] Authentication middleware correctly authenticates users based on HTTP-only cookies.
- [x] Users can only perform CRUD operations on their own application records.
- [x] Input data is properly validated with appropriate error messages.
- [x] Comprehensive unit and integration tests are written and passing.
- [x] API documentation is complete with example requests and responses.
- [x] Code follows the project's coding standards and best practices.

---

**Additional Context**
- Refer to the [API Design Guidelines](https://example.com/api-guidelines) for best practices.
- Existing user authentication system using HTTP-only cookies should be integrated.

---

**Labels**: `feature`, `CRUD`, `backend`, `Go`, `Gin`, `HTTP-only Cookie`, `documentation`, `testing`

---
