### ISSUE TITLE
Add functionality to update the status of job applications

### ISSUE THREAD

**Issue by R-Thibault** [R-Thibault/FollowMyJobs#22]
# [Update Application Status Endpoint]: Add functionality to update the status of job applications

---

## **Summary**
- **URL**: `POST /api/applications/{id}/status`
- **Purpose**: Allow users to update the status fields (`Applied`, `Response`, `FollowUp`) of a specific job application.
- **Authentication**: Required. Only the owner of the application can perform this operation.

---

## **Tasks**
- [ ] Define the `POST /api/applications/{id}/status` route in Gin.
- [ ] Implement the controller function to update the application status.
- [ ] Implement authorization to ensure users can update only their own applications.
- [ ] Handle error cases for validation, unauthorized access, and non-existent applications.
- [ ] Write integration tests for the endpoint.
- [ ] Document the endpoint.

---

### **Request Data**
```json
{
  "Applied": "boolean, optional",
  "Response": "boolean, optional",
  "FollowUp": "boolean, optional"
}
```

### **Response**
- **Success** (`200 OK`):
  ```json
  {
    "id": 1,
    "applied": true,
    "response": true,
    "follow_up": false,
    "updated_at": "2024-05-01T12:00:00Z"
  }
  ```

- **Error** (`4XX/5XX`):
  - **Validation Error** (`400 Bad Request`):
    ```json
    {
      "error": "validation_error",
      "message": "Invalid value for 'Applied'."
    }
    ```
  - **Unauthorized Access** (`403 Forbidden`):
    ```json
    {
      "error": "forbidden",
      "message": "You do not have permission to update this application."
    }
    ```
  - **Not Found** (`404 Not Found`):
    ```json
    {
      "error": "not_found",
      "message": "Application not found."
    }
    ```

---

## **Detailed Description**
This endpoint is designed to allow users to update the status fields (`Applied`, `Response`, `FollowUp`) of their job applications. It will ensure that only the application owner can perform this action, and input data will be validated to prevent invalid updates.

---

## **Acceptance Criteria**
- [ ] The `POST /api/applications/{id}/status` endpoint is implemented and functions as expected.
- [ ] Authentication is required and properly verified using HTTP-only cookies.
- [ ] Users can only update their own applications.
- [ ] All edge cases (non-existent application, unauthorized access, invalid input) are handled with appropriate error messages.
- [ ] Integration tests are written and passing.
- [ ] Documentation is complete.

---

**Additional Context**
- Refer to the existing authentication and authorization middleware for integration.

---

**Labels**: `feature`, `API`, `CRUD`, `documentation`, `testing`

---
