### ISSUE TITLE
Enable pagination for the list of job applications

### ISSUE THREAD

**Issue by R-Thibault** [R-Thibault/FollowMyJobs#24]
---
##  Enable pagination for the list of job applications
---

## **Summary**

- **URL**: `GET /applications-by-user`
- **Purpose**: Add pagination to the application list to improve performance and user experience when retrieving large datasets.
- **Authentication**: Required. Only the authenticated user can access their applications.

---

## **Tasks**

- [x] Update the `GET /applications-by-user` endpoint to support pagination.
- [x] Accept `page` and `page_size` as query parameters.
- [x] Validate that `page` and `page_size` are positive integers.
- [x] Implement logic to fetch only the requested subset of applications using Gorm.
- [x] Return metadata about the pagination (e.g., current page, total pages, total items).
- [x] Handle error cases, such as invalid query parameters.
- [x] Document the updated endpoint with examples of paginated responses.

---

### **Request Data**

- **Query Parameters**:
  - `page`: integer, required
  - `page_size`: integer, required

### Example:

`GET /applications-by-user?page=1&page_size=10`

---

### **Response**

- **Success** (`200 OK`):

  ```json
  {
    "data": [
      {
        "id": 1,
        "user_id": 123,
        "url": "https://example.com/job",
        "title": "Software Engineer",
        "company": "Example Corp",
        "location": "New York, NY",
        "description": "Job description here...",
        "salary": "$100,000",
        "job_type": "Full-Time",
        "applied": true,
        "response": false,
        "follow_up": false,
        "created_at": "2024-04-27T10:00:00Z",
        "updated_at": "2024-04-27T10:00:00Z"
      }
    ],
    "pagination": {
      "current_page": 1,
      "page_size": 10,
      "total_pages": 5,
      "total_items": 50
    }
  }
  ```

- **Error** (`400 Bad Request`):
  ```json
  {
    "error": "validation_error",
    "message": "Invalid value for 'page'."
  }
  ```

---

## **Detailed Description**

This enhancement adds pagination support to the `GET /applications-by-user` endpoint. By including `page` and `page_size` as query parameters, users can control the size and offset of the data returned. Metadata such as the current page, total pages, and total items will provide users with context about their request.

---

## **Acceptance Criteria**

- [x] The `GET /applications-by-user` endpoint supports `page` and `page_size` query parameters.
- [x] Only the requested subset of applications is returned.
- [x] Pagination metadata is included in the response.
- [x] Input validation ensures `page` and `page_size` are positive integers.
- [x] Error handling is implemented for invalid parameters or edge cases.
- [x] API documentation is complete with examples of paginated requests and responses.

---

**Additional Context**

- Use Gorm's `Limit` and `Offset` methods to implement pagination.
- Ensure that the total number of items is calculated efficiently for large datasets.

---

**Labels**: `feature`, `API`, `pagination`, `documentation`, `testing`

---
