### ISSUE TITLE
Enable search and filtering for job applications

### ISSUE THREAD

**Issue by R-Thibault** [R-Thibault/FollowMyJobs#26]
---

# [Add Search and Filter to Application List Endpoint]: Enable search and filtering for job applications

---

## **Summary**
- **URL**: `GET /api/applications`
- **Purpose**: Add search and filtering capabilities to the application list to allow users to find specific applications based on criteria like title, URL, creation date, or status.
- **Authentication**: Required. Only the authenticated user can access their applications.

---

## **Tasks**
- [x] Update the `GET /api/applications` endpoint to support search and filtering.
- [x] Accept the following query parameters:
  - `search`: string, optional (matches `title` or `url`)
  - `created_at_order`: string, optional (`asc` or `desc` for `CreatedAt`)
  - `status`: string, optional (filter by `Applied`, `Response`, `FollowUp` fields)
- [x] Implement logic to apply search and filter conditions using Gorm.
- [x] Validate the query parameters for correct types and valid values.
- [ ] Document the updated endpoint with examples of search and filtered responses.

---

### **Request Data**
- **Query Parameters**:
  - `search`: string, optional
  - `created_at_order`: string, optional (`asc` or `desc`)
  - `status`: string, optional (`applied`, `response`, `follow_up`)

### Example:
`GET /api/applications?search=engineer&created_at_order=asc&status=applied`

---

### **Response**
- **Success** (`200 OK`):
  ```json
  {
    "data": [
      {
        "id": 1,
        "user_id": 123,
        "url": "https://example.com/job",
        "title": "Software Engineer",
        "company": "Example Corp",
        "location": "New York, NY",
        "description": "Job description here...",
        "salary": "$100,000",
        "job_type": "Full-Time",
        "applied": true,
        "response": false,
        "follow_up": false,
        "created_at": "2024-04-27T10:00:00Z",
        "updated_at": "2024-04-27T10:00:00Z"
      }
    ],
    "metadata": {
      "total_items": 10,
      "filters": {
        "search": "engineer",
        "created_at_order": "asc",
        "status": "applied"
      }
    }
  }
  ```

- **Error** (`400 Bad Request`):
  ```json
  {
    "error": "validation_error",
    "message": "Invalid value for 'created_at_order'."
  }
  ```

---

## **Detailed Description**
This enhancement adds search and filtering capabilities to the `GET /api/applications` endpoint. Users can:
- Search by `title` or `url` using the `search` parameter (case-insensitive partial match).
- Filter results by creation date (`CreatedAt`) with ascending or descending order.
- Filter results by application status (`Applied`, `Response`, `FollowUp`) using the `status` parameter.

---

## **Acceptance Criteria**
- [ ] The `GET /api/applications` endpoint supports `search`, `created_at_order`, and `status` query parameters.
- [ ] Search results match partial and case-insensitive queries for `title` or `url`.
- [ ] Filters for `created_at_order` and `status` work correctly.
- [ ] Validation ensures query parameters have valid values.
- [ ] Appropriate metadata is included in the response (e.g., total items, applied filters).
- [ ] Error handling is implemented for invalid parameters or edge cases.
- [ ] API documentation is complete with examples of search and filtered requests and responses.

---

**Additional Context**
- Use Gorm’s `Where` and `Order` methods to implement search and filtering.
- Optimize database queries for large datasets to maintain performance.

---

**Labels**: `feature`, `API`, `search`, `filter`, `documentation`, `testing`

---
