### ISSUE TITLE
Database Configuration and Seed Data

### ISSUE THREAD

**Issue by R-Thibault** [R-Thibault/FollowMyJobs#4]
### [Title]: Database Configuration and Seed Data

---

#### **Summary**
- **URL**: None
- **Purpose**: Set up database configuration and add seed data
- **Authentication**: None

---

### **Tasks**
- [x] Configure `config/database.go` to connect to the database using environment variables
- [x] Implement database models according to PDM
- [x] Implement `config/application_seed.go` and `config/user_seed.go` to add sample data for applications and users
- [x] Update README with instructions for setting up the database and running seed scripts

---

#### **Request Data**
None

#### **Response**
None

---

### **Detailed Description**
Set up database configuration and add seed data scripts in the `config/` directory to facilitate development and testing.

---

### **Acceptance Criteria**
- [ ] Connexion to database is setup
- [ ] Database created according to PDM
- [ ] Automatic seeding when in developement environment
- [ ] README explain how to setup database and how seeding work

---

**Additional Context**
(Optional) None

---

**Labels**: `backend`,`documentation`

---
