### ISSUE TITLE
Implement User Login Endpoint

### ISSUE THREAD

**Issue by R-Thibault** [R-Thibault/FollowMyJobs#5]
### [Title]: Implement User Login/Logout Endpoint

---

#### **Summary**
- **URL**: `[POST] /api/v1/users/login`
- **Purpose**: Allows existing users to log in by validating their credentials and returning an authentication token.
- **Authentication**: Not required for accessing this endpoint, but successful login will issue a JWT for future requests.
---

### **Tasks**
- [x] Define the login route in `routes/routes.go`. Define logout route in `routes/routes.go`.
- [x] Create a LoginUser function in `controllers/auth_controller.go` to handle login requests.Create a LogoutUser function too.
- [x] Implement login logic in `services/auth_service.go` to:
     - Retrieve user by username/email.
     - Verify the user’s password (using the hashing utility in pkg/hash).
     - Generate a JWT token upon successful authentication (using pkg/jwt).
 - [x] Implement logout logic in `services/auth_service.go` to:
     - Retrieve user with context.
     - Delete cookie and jwt create for user.    
- [x] Add an interface in services/user/auth_services_interface.go to ensure mocking capability for test.
- [x] Write integration test, covering both successful and failed login attempts. With mock, to cover test of components.

---

#### **Request Data**
<pre><code>json
{
  "username": "string, required",
  "password": "string, required"
}
</code></pre>

#### **Response**
- **Success** (`[Status Code]`):
  <pre><code>json
  {
   "token": "string",
   "user": {
     "id": "string",
     "email": "string"
  }
  </code></pre>

- **Error** (`[Status Code]`):
  <pre><code>json
  {
   "error": "Unauthorized",
   "message": "Invalid username or password"
  }
  </code></pre>

---

### **Detailed Description**
This endpoint should validate the user’s credentials and, upon success, issue a JSON Web Token (JWT) for session management. The token will be used in subsequent requests for authentication. Passwords should be verified using the hashing utility to ensure security.

---

### **Acceptance Criteria**
- [x] Users can successfully log in with correct credentials and receive a JWT.
- [ ] Invalid login attempts return a 401 Unauthorized response.
- [x] Full test coverage for controller and service functions related to login.
---

**Additional Context**
(Optional) Add links, references, or other resources related to this issue.

---

**Labels**: `feature`, `authentication`, `backend`

---
