### ISSUE TITLE
Implement User Registration Endpoint

### ISSUE THREAD

**Issue by R-Thibault** [R-Thibault/FollowMyJobs#6]
### [Title]: Implement User Registration Endpoint

---

#### **Summary**
- **URL**: `[POST] /api/v1/users/registrer`
- **Purpose**: Allow users to create a account with an email validation by OTP
- **Authentication**: None

---

### **Tasks**
- [x] Define the registration route in `route/routes.go`.
- [x] Create a RegisterUser function in `controller/user_controller.go` to handle registration requests.
- [x] Implement logic in `services/user/user_services.go` to:
    - Verify if user do not exists
    - Compare password and confirm password
    - hash password
    - register user on database with an UUID generate during creation
- [x] Add an interface in `services/user/user_services_interface.go` to ensure mocking capability for test
- [x] Write integration test to ensure all components work together and use mocked interface to ensure function in components work properly
- [x] Add Documentation for frontend 

---

#### **Request Data**
<pre><code>json
{
  "email": "string, required",
  "password": "string, required",
  "confirmPassword": "string, required"
}
</code></pre>

#### **Response**
- **Success** (`[Status Code]`):
  <pre><code>json
  {
    "succes": "StatusOK",
    "message": "user successfully resgistred"
  }
  </code></pre>

- **Error** (`[Status Code]`):
  <pre><code>json
  {
    "error": "StatusBadRequest",
    "message": "error during registration process"
  }
  </code></pre>

---

### **Detailed Description**
This endpoint should create an user with information given and a UUID generated upon creation. The UUID will be use in the JWTToken. 

---

### **Acceptance Criteria**
- [x] User can successfully registrer
- [x] Invalid registration attempt will return proper response and error message
- [x] Full Test coverage for controller and service functions related to registration
- [x] Documentation for frontend development such as route, request data...

---

**Additional Context**
Error message and Code can be adapted.

---

**Labels**: `feature`, `backend`, `documentation`

---
